// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCalculator.Data;

#nullable disable

namespace WebCalculator.Migrations
{
    [DbContext(typeof(WebCalculatorContext))]
    [Migration("20230215092246_PrvniMigraceNewModelCalculator")]
    partial class PrvniMigraceNewModelCalculator
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebCalculator.Models.Calculator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<float>("DruheCislo")
                        .HasColumnType("real");

                    b.Property<string>("Operace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PrvniCislo")
                        .HasColumnType("real");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<float>("Vysledek")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Calculator");
                });
#pragma warning restore 612, 618
        }
    }
}
